# Generated by Django 5.0.1 on 2024-01-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
