# Generated by Django 5.0.1 on 2024-01-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='coursetheme',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
