# Generated by Django 5.0.1 on 2024-01-08 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_name_alter_coursetheme_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bought_user',
            field=models.ManyToManyField(related_name='bought_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
