# Generated by Django 5.0.1 on 2024-01-08 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_bought_user_alter_course_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bought_user',
            field=models.ManyToManyField(null=True, related_name='bought_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
