# Generated by Django 5.0.1 on 2024-01-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_picture', models.ImageField(upload_to='~/medias/profile_pictures')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('has_access', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
